version: '3.8'
services:
  stats-server:
    build: ./ewm-stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstats

  stats-db:
    image: postgres:14.7-alpine
    container_name: ewm-stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
